### ISSUE TITLE
Injecting infrastructure services into sagas

### ISSUE THREAD

**Issue by coolg54321** [broadway/broadway-saga#7]
May be its not an issue with broadway, more of a question on its implementation,

Is it ok to inject services like doctrine/repositories into sagas, if i need some information from the database depending on the context (In the perfect DDD sense), because now your domain depends on infrastructure layer

That is something like

```
    company.domain.saga.invoice_clearing:
        class: Company\AccountingBundle\Domain\Saga\InvoiceClearingSaga
        tags:
            - { name: broadway.saga, type: invoice }
        arguments:
          - "@broadway.command_handling.command_bus"
          - "@broadway.uuid.generator"
         -  "@doctrine"
```

I have the same question for command handlers as well (because technically its possible to do in broadway)
